### ISSUE TITLE
TODO M3

### ISSUE THREAD

**Issue by xkosorin** [jarkovic/PA165-ice-hockey-manager#62]
- [x] The following sequence of commands should start the web application: “mvn clean install && cd manager-springmvc && mvn cargo:run”.
- [x] The web application must be available at the following HTTP context http://localhost:8080/pa165.
- [x] Application should use in-memory database.
- [x] Implement the user interface using Spring MVC.
- [x] The user interface should allow to carry out all business functions of your system.
- [x] Fill in all the necessary data automatically.
- [x] Make sure there are validations implemented at the user interface level.
- [x] User interface should use either a Facade layer or REST layer to access the system. Do not directly access database and do not directly use the Service layer.
- [x] The web interface layer may reside in a separate maven module.
- [x] Each member of the team must implement (mostly independently) part of user interface. Including controllers and views.
- [x] Your application should have a basic REST interface/API.
- [x] At least one entity and operations on that entity must be exposed.
- [x] This is mainly to demonstrate you can implement this, it is not necessary to have all application functions accessible through this interface.
- [x] The REST API must be accessible at http://localhost:8080/pa165/rest
- [x] It is not required to have the interface secured.
- [x] You should include a README file with instructions about how to test the REST interface (e.g. CURL commands for the command line).
- [x] There should be at least two roles in the system (e.g. Administrator, User). Each role should have some differences in user interface or in capabilities.
- [x] There should be a login form (not HTTP Basic).
- [x] Registration is NOT required. You can prefill the users and their passwords in the database.
- [x] Password should not be saved in the database in open form.

- [x] remove unused imports
- [x] Javadoc not matching
- [x] Facade chybí update metoda

**Comment by xkosorin** [comment]
- [x] missing create/update/delete operations in both UI and controllers
- [x] no difference between admin and user
- [x] REST is working for me but the JSON seems to be trimmed
- [x] /pa165/rest/match/1/winner - I would expect something simple not a whole bunch of team data
- [x] no possibility to create or delete new player
- [x] I didn’t find match simulation
- [x] make sure there are validations implemented at the user interface level
- [x] some queries did not return correct JSON file
- [ ] Refine the GUI so that the presented application looks as appealing as possible
- [x] add logging to everything
- [ ] no edit team UI
- [ ] delete team not working properly
- [ ] add team UI re-do
- [x] matches UI weird bar?
- [x] add match UI improve
